name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Move Build to Server
        run: mv client/build server/build

      - name: Prepare Server Directory for Deployment
        working-directory: server
        run: |
          git init
          git remote add heroku https://git.heroku.com/mt-portfolio.git
          git add .
          git commit -m "Deploy to Heroku"

      - name: Deploy to Heroku
        working-directory: server
        run: |
          git push heroku main --force
