name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Move Build to Server
        run: mv client/build server/build

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mt-portfolio"
          heroku_email: "mtik.philosopher@gmail.com"
          dontuseforce: 1 
